---

- name: Build AvalancheGo
  hosts: localhost
  become: no

  tasks:
    - name: Run local build script
      shell: ./scripts/build.sh

- name: Deploy AvalancheGo
  hosts: nodes
  become: yes

  vars:
    clear_db: true  # set to true to clear the database

  tasks:

    - name: Stop AvalancheGo service
      systemd:
        name: avalanchego.service
        state: stopped

    - name: Copy local avalanchego file to remote server
      copy:
        src: build/avalanchego
        dest: /home/ubuntu/avalanche-node
        mode: "0775"

    - name: Clear database if requested
      when: clear_db == true
      file:
        path: /home/ubuntu/.avalanchego/db/fuji/v1.4.5/
        state: absent

    # - name: Clear chain if requested
    #   when: clear_db == true
    #   file:
    #     path: /home/ubuntu/.avalanchego/chainData
    #     state: absent

    - name: Start AvalancheGo service
      systemd:
        name: avalanchego.service
        state: started