# Build a macos release from the avalanchego repo

name: build-macos-release

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to include in artifact name'
        required: true
  push:
    tags:
      - "*" # Push events to every tag

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-mac:
    # The type of runner that the job will run on
    runs-on: macos-12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '~1.19.6'
          check-latest: true
      - run: go version

      # Runs a single command using the runners shell
      - name: Build the avalanchego binary
        run: ./scripts/build.sh

      - name: Try to get tag from git
        if: "${{ github.event.inputs.tag == '' }}"
        id: get_tag_from_git
        run: |
          echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        shell: bash

      - name: Try to get tag from workflow dispatch
        if: "${{ github.event.inputs.tag != '' }}"
        id: get_tag_from_workflow
        run: |
          echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
        shell: bash

      - name: Create zip file
        run: 7z a avalanchego-macos-${TAG}.zip build/avalanchego
        env:
          TAG: ${{ env.TAG }}

      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.4.0
        with:
          provider: digitalocean # default is linode
          region: 'nyc3'
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload file to S3
        run: s3cmd put avalanchego-macos-${{ env.TAG }}.zip s3://${BUCKET}/macos/
        env:
          BUCKET: ${{ secrets.BUCKET }}

      - name: Save as Github artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: avalanchego-macos-${{ env.TAG }}.zip
      
      - name: Cleanup
        run: |
          rm -rf ./build
