name: build-amd64-debian-packages

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to include in artifact name'
        required: true
  push:
    tags:
      - "*"

jobs:
  build-jammy-amd64-package:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '~1.19.6'
          check-latest: true
      - run: go version

      - name: Build the avalanchego binaries
        run: ./scripts/build.sh

      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.4.0
        with:
          provider: digitalocean # default is linode
          region: 'nyc3'
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Try to get tag from git
        if: "${{ github.event.inputs.tag == '' }}"
        id: get_tag_from_git
        run: |
          echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        shell: bash

      - name: Try to get tag from workflow dispatch
        if: "${{ github.event.inputs.tag != '' }}"
        id: get_tag_from_workflow
        run: |
          echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
        shell: bash

      - name: Create debian package
        run: ./.github/workflows/build-deb-pkg.sh
        env:
          PKG_ROOT: /tmp/avalanchego
          TAG: ${{ env.TAG }}
          BUCKET: ${{ secrets.BUCKET }}
          ARCH: "amd64"
          RELEASE: "jammy"

      - name: Save as Github artifact
        uses: actions/upload-artifact@v3
        with:
          name: jammy
          path: /tmp/avalanchego/avalanchego-${{ env.TAG }}-amd64.deb

      - name: Cleanup
        run: |
          rm -rf ./build
          rm -rf /tmp/avalanchego

  build-focal-amd64-package:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '~1.19.6'
          check-latest: true
      - run: go version

      - name: Build the avalanchego binaries
        run: ./scripts/build.sh

      - name: Try to get tag from git
        if: "${{ github.event.inputs.tag == '' }}"
        id: get_tag_from_git
        run: |
          echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        shell: bash

      - name: Try to get tag from workflow dispatch
        if: "${{ github.event.inputs.tag != '' }}"
        id: get_tag_from_workflow
        run: |
          echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
        shell: bash

      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.4.0
        with:
          provider: digitalocean # default is linode
          region: 'nyc3'
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Create debian package
        run: ./.github/workflows/build-deb-pkg.sh
        env:
          PKG_ROOT: /tmp/avalanchego
          TAG: ${{ env.TAG }}
          BUCKET: ${{ secrets.BUCKET }}
          ARCH: "amd64"
          RELEASE: "focal"

      - name: Save as Github artifact
        uses: actions/upload-artifact@v3
        with:
          name: focal
          path:  /tmp/avalanchego/avalanchego-${{ env.TAG }}-amd64.deb

      - name: Cleanup
        run: |
          rm -rf ./build
          rm -rf /tmp/avalanchego
